# Generated by Django 2.2.10 on 2020-02-26 02:22

import analysis.models.flow_model
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_number', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('duration_sec', models.IntegerField()),
                ('hard_timeout', models.IntegerField()),
                ('byte_count', models.IntegerField()),
                ('length', models.IntegerField()),
                ('actions', djongo.models.fields.EmbeddedField(model_container=analysis.models.flow_model.Actions, null=True)),
                ('duration_nsec', models.IntegerField()),
                ('packet_count', models.IntegerField()),
                ('idle_timeout', models.IntegerField()),
                ('cookie', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('table_id', models.IntegerField()),
                ('match', djongo.models.fields.EmbeddedField(model_container=analysis.models.flow_model.Match, null=True)),
            ],
        ),
    ]
